### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by jusce17** [SubhadityaMukherjee/functionFinder#2]
Hey @SubhadityaMukherjee 
Currently (I believe), there is no license associated with project, would be nice to add a MIT like license so people can know it is open source and they can also contribute on it

Thanks,
Eden

**Comment by jusce17** [comment]
In case you wanna add it:
on the main [web page](https://github.com/SubhadityaMukherjee/functionFinder)
click add file > create new file
Name it LICENSE.md or LICENSE.txt to show up the license picker

**Comment by SubhadityaMukherjee** [comment]
Hello @jusce17. Thank you for your interest :) 
I have updated the license
